apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-webapp
  labels:
    app: angular-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-webapp
  template:
    metadata:
      labels:
        app: angular-webapp
    spec:
      containers:
      - name: angular-webapp
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-smarttradz-angular
        command: ["/bin/sh","-c"]
        args: ["sed -i 's/listen  .*/listen 3000;/g' /etc/nginx/conf.d/default.conf && sed -i 's/listen  .*/listen 3000;/g' /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "3072Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms1024m -Xmx2048m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - main-worker

---

apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
  labels:
    run: angular-webapp
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    run: angular-webapp
