apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-webapp
  labels:
    app: angular-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-webapp
  template:
    metadata:
      labels:
        app: angular-webapp
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-smarttradz-angular
        name: angular-webapp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "3072Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms1024m -Xmx2048m"
        ports:
        - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
  labels:
    app: angular-webapp
spec:
  selector:
    app: angular-webapp
  ports:
  - port: 3000
    protocol: TCP
