apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  selector:
    matchLabels:
      run: common-service
  replicas: 1
  template:
    metadata:
      labels:
        run: common-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-commons
        name: common-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1536Mi"
        env:
          - name: APP_NAME
            value: "commons-service"
          - name: CONFIG_URI
            value: "http://config-server:8888"
          - name: _JAVA_OPTIONS
            value: "-Xms512m -Xmx1024m"
        ports:
        - containerPort: 8100
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: common-service
  labels:
    run: common-service
spec:
  ports:
  - port: 8100
    protocol: TCP
  selector:
    run: common-service
