apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-config
        name: config-server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1536Mi"
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: "password"
        - name: SEARCH_LOCATION
          value: "classpath:/pmtdev"
        - name: _JAVA_OPTIONS
          value: "-Xms512m -Xmx1024m"
        ports:
        - containerPort: 8888
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: config-server
