apiVersion: apps/v1
kind: Deployment
metadata:
  name: deal-management-service
spec:
  selector:
    matchLabels:
      run: deal-management-service
  replicas: 1
  template:
    metadata:
      labels:
        run: deal-management-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-deal-management
        name: deal-management-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "3072Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms1024m -Xmx2048m"
        ports:
        - containerPort: 8090
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: deal-management-service
  labels:
    run: deal-management-service
spec:
  type: ClusterIP
  ports:
    - port: 8090
  selector:
    run: deal-management-service
