apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      run: eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        run: eureka-server
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-eureka
        name: eureka-server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1536Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms512m -Xmx1024m"
        ports:
        - containerPort: 8761
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    run: eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
  selector:
    run: eureka-server
