apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      run: identity-service
  replicas: 1
  template:
    metadata:
      labels:
        run: identity-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-identity-management
        name: identity-service
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "1536Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms512m -Xmx1024m"
        ports:
        - containerPort: 8093
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    run: identity-service
spec:
  ports:
    - port: 8093
      protocol: TCP
  selector:
    run: identity-service
