apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  selector:
    matchLabels:
      run: pricing-service
  replicas: 1
  template:
    metadata:
      labels:
        run: pricing-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-pricing
        name: pricing-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "3072Mi"
        env:
          - name: APP_NAME
            value: "pricing-service"
          - name: CONFIG_URI
            value: "http://config-server:8888"
          - name: _JAVA_OPTIONS
            value: "-Xms1024m -Xmx2048m"
        ports:
        - containerPort: 8094
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  labels:
    run: pricing-service
spec:
  ports:
  - port: 8094
    protocol: TCP
  selector:
    run: pricing-service
