apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategise-service
spec:
  selector:
    matchLabels:
      run: strategise-service
  replicas: 1
  template:
    metadata:
      labels:
        run: strategise-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-strategise
        name: strategise-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "3072Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms1024m -Xmx2048m"
        ports:
        - containerPort: 8101
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: strategise-service
  labels:
    run: strategise-service
spec:
  ports:
  - port: 8101
    protocol: TCP
  selector:
    run: strategise-service
