apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-service
spec:
  selector:
    matchLabels:
      run: transport-service
  replicas: 1
  template:
    metadata:
      labels:
        run: transport-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-transport
        name: transport-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "768Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms256m -Xmx312m"
        ports:
        - containerPort: 8108
        volumeMounts:
          - name: logs
            mountPath: /logs
            subPath: transport
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: transport-service
  labels:
    run: transport-service
spec:
  ports:
  - port: 8108
    protocol: TCP
  selector:
    run: transport-service
