apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-service
spec:
  selector:
    matchLabels:
      run: etl-service
  replicas: 1
  template:
    metadata:
      labels:
        run: etl-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/prod/iocl-etl
        name: etl-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1536Mi"
          limits:
            memory: "3072Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms1024m -Xmx2048m"
        ports:
        - containerPort: 8095
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: etl-service
  labels:
    run: etl-service
spec:
  ports:
  - port: 8095
    protocol: TCP
  selector:
    run: etl-service
