apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 80
    nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: zuul-server
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 8000
    nodePort: 30030

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 88
    nodePort: 30003
