apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: angular-webapp
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-smarttradz-angular:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: config-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-config:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: eureka-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-eureka:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: zuul-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-zuul:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: identity-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-identity-management:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: common-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-commons:latest
        volumeMounts:
        - name: nfs-v
          mountPath: /file-repo
          subPath: common/file-repo
        - name: nfs-v
          mountPath: /upload-dir
          subPath: common/upload-dir
        - name: nfs-v
          mountPath: /archive-dir
          subPath: common/archive-dir
        - name: nfs-v
          mountPath: /logs
          subPath: logs/common
      volumes:
        - name: nfs-v
          nfs:
            server: ip-10-0-10-202.ec2.internal
            path: /share/nfsdata
            readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterdata-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: masterdata-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-master-data:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: auth-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-auth:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: integration-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-integration:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: volume-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-volume:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deal-management-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: deal-management-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-deal-management:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: pricing-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-pricing:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: workflow-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-workflow-server:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: etl-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-etl:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: industry-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: industry-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-industry-analysis:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-power-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: pricing-power-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-pricing-power:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: ocr-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-ocr:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 0
  template:
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
