apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: logs-vol1
    volumeAttributes:
      source: "//10.0.10.202/pmt"
  # flexVolume:
  #   driver: "fnordian/cv"
  #   readOnly: false
  #   options:
  #     source: "//10.0.10.202/pmt"
  #     mountOptions: "dir_mode=0700,file_mode=0600"
  #     cifsuser: "nobody"
  #     cifspass: "nobody"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: logs-pv
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
