apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      run: config-server
  replicas: 1
  template:
    metadata:
      labels:
        run: config-server
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/uat/iocl-config
        name: config-server
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1024Mi"
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: "password"
        - name: SEARCH_LOCATION
          value: "classpath:/pmtuat"
        - name: _JAVA_OPTIONS
          value: "-Xms256m -Xmx512m"
        ports:
        - containerPort: 8888
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    run: config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    run: config-server
