apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-power-service
spec:
  selector:
    matchLabels:
      run: pricing-power-service
  replicas: 1
  template:
    metadata:
      labels:
        run: pricing-power-service
    spec:
      containers:
      - image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/prod/iocl-pricing-power
        name: pricing-power-service
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "768Mi"
        env:
          - name: _JAVA_OPTIONS
            value: "-Xms256m -Xmx312m"
        ports:
        - containerPort: 8097
      imagePullSecrets:
        - name: smarttradzt-ecr
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: pricing-power-service
  labels:
    run: pricing-power-service
spec:
  ports:
  - port: 8097
    protocol: TCP
  selector:
    run: pricing-power-service
