apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
  labels:
    run: angular-webapp
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 80
    nodePort: 30000
  selector:
    run: angular-webapp

---

apiVersion: v1
kind: Service
metadata:
  name: zuul-server
  labels:
    run: zuul-server
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 8000
    nodePort: 30030
  selector:
    run: zuul-server

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
  selector:
    run: nginx