apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: config-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-config:1.2.1-DEVT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  template:
    spec:
      containers:
      - name: eureka-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-eureka:1.2.1-DEVT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-server
spec:
  template:
    spec:
      containers:
      - name: zuul-server
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-zuul:1.2.1-DEVT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  template:
    spec:
      containers:
      - name: common-service
        image: 395321600628.dkr.ecr.ap-southeast-1.amazonaws.com/iocl-commons:1.2.1-DEVT
        volumeMounts:
        - name: common-vm
          mountPath: /file-repo
          subPath: common/file-repo
        - name: common-vm
          mountPath: /upload-dir
          subPath: common/upload-dir
        - name: common-vm
          mountPath: /archive-dir
          subPath: common/archive-dir
        - name: logs-vm
          mountPath: /logs
          subPath: logs
      volumes:
        - name: common-vm
          persistentVolumeClaim:
            claimName: common-pvc
        - name: logs-vm
          persistentVolumeClaim:
            claimName: logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zuul-server
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30030
