apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 8090
    name: my-port
    targetPort: 80
    nodePort: 30000
  selector:
    app: angular-webapp

---

apiVersion: v1
kind: Service
metadata:
  name: zuul-server
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 8091
    name: my-port
    targetPort: 8000
    nodePort: 30030
  selector:
    app: zuul-server

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 8092
    name: my-port
    targetPort: 80
    nodePort: 30003